vuepress-theme-hope/vuepress-theme-hope

packages/comment/src/node/i18n.ts
packages/components/src/node/i18n.ts
packages/copy-code/src/node/i18n.ts
packages/md-enhance/src/node/i18n.ts
packages/photo-swipe/src/node/i18n.ts
packages/pwa/src/node/i18n.ts
packages/reading-time/src/node/i18n.ts
packages/shared/src/i18n/config.ts
packages/shared/src/i18n/types.ts

Hello Mr.Hope, thanks for the excellent Vuepress theme! :)
I'd really like to use it with a Brazilian Portuguese locale, and I'd like to contribute with some translations.
Would you please tell me if this PR needs more work?

feat: add pt-BR language support

---

packages/copy-code2/src/node/i18n.ts

This PR includes very minor updates to the English text for copying code. This updated version of the text is slightly more natural for English speakers.

fix: minor update to english code copy text

---

CHANGELOG.md
demo/CHANGELOG.md
demo/src/home.md
demo/src/zh/home.md
docs/theme/CHANGELOG.md
docs/theme/src/README.md
docs/theme/src/config/plugins/pwa.md
docs/theme/src/zh/README.md
docs/theme/src/zh/guide/markdown/flowchart.md
packages/create/template/en-US/home.md
packages/create/template/i18n/home.md
packages/create/template/i18n/zh/home.md
packages/create/template/zh-CN/home.md
packages/md-enhance/src/client/demo/code.ts
packages/md-enhance/src/client/demo/dom.ts
packages/md-enhance/src/client/demo/index.ts
packages/md-enhance/src/client/demo/typings.ts
packages/md-enhance/src/client/styles/code-demo.scss
packages/theme/CHANGELOG.md
packages/theme/src/client/module/blog/components/BlogHero.ts
packages/theme/src/client/module/blog/styles/blog-hero.scss

Quick Enable Updated

---

packages/comment2/src/node/locales.ts
packages/components/src/node/locales.ts
packages/copy-code2/src/node/locales.ts
packages/copyright2/src/node/locales.ts
packages/md-enhance/src/node/locales.ts
packages/photo-swipe/src/node/locales.ts
packages/pwa2/src/node/locales.ts
packages/reading-time2/src/node/locales.ts
packages/shared/src/node/locales/config.ts
packages/theme/src/node/locales/es.ts
packages/theme/src/node/locales/index.ts

This PR will add I18n support for the Spanish language.

feat: add I18n support for spanish

---

packages/copy-code2/src/client/composables/setup.ts
packages/copy-code2/src/node/plugin.ts

there are some typos in `copy-code2` and I fixed them. 😝

chore(copy-code2): fix typos

---

docs/components/src/config.md
docs/components/src/zh/config.md
docs/theme/src/config/theme/appearance.md
docs/theme/src/zh/config/theme/appearance.md
packages/components/src/shared/options.ts
packages/theme/src/shared/options/appearance.ts

This PR replaces #2091  as a rebased branch instead.
I tried to find the file about "font-awesome" and modified what I thought needed to be modified.
At the same time, I reorganized the history of the commits to make it look neater.

docs: correct iconAssets config value

---

packages/theme/src/client/components/HomeFeatures.ts

fix: home page icon

---

packages/md-enhance/__tests__/unit/__fixtures__/deepIncludeLink.md
packages/md-enhance/__tests__/unit/__fixtures__/relative/includeLink.md
packages/md-enhance/__tests__/unit/include.spec.ts
packages/md-enhance/src/node/markdown-it/attrs.ts
packages/md-enhance/src/node/markdown-it/include.ts
packages/md-enhance/src/shared/include.ts

fix(md-enhance): the relative image/link path error in the include markdown file.

---

packages/pwa2/src/client/composables/setup.ts

发布线上访问报错：
TypeError: Cannot read properties of undefined (reading 'controller')

TypeError: Cannot read properties of undefined (reading 'controller')

---

docs/theme/src/zh/demo.md

add my blog as a demo, thanks for hope's contribution

docs(theme): update demo

---

docs/theme/src/zh/demo.md

添加项目案例-小佟的学习笔记站点，基于vuepress-theme-hope构建

更新项目案例-小佟的学习笔记

---

packages/comment2/src/node/locales.ts
packages/components/src/node/locales/backToTop.ts
packages/components/src/node/locales/catalog.ts
packages/components/src/node/locales/pdf.ts
packages/copy-code2/src/node/locales.ts
packages/copyright2/src/node/locales.ts
packages/md-enhance/src/node/locales.ts
packages/photo-swipe/src/node/locales.ts
packages/pwa2/src/node/locales.ts
packages/reading-time2/src/node/locales.ts
packages/search-pro/src/node/locales.ts
packages/shared/src/node/locales/config.ts
packages/theme/src/node/locales/fi.ts
packages/theme/src/node/locales/index.ts

Hello!
This pull request adds 🇫🇮 Finnish language support to the theme.

feat(theme): Add Finnish language support

---

docs/theme/src/guide/interface/icon.md

Remove erroneus TS tab with no content.

Remove extra TS tab

---

packages/shared/src/node/utils/dayjs/index.ts
packages/theme/src/node/locales/de.ts

Fix build issues when using de-DE locale

Fix locale configuration for de-DE

---

docs/theme/src/zh/config/frontmatter/info.md

docs(theme): update translates

---

docs/theme/src/guide/advanced/presets.md
docs/theme/src/zh/guide/advanced/presets.md

为项目主页的特性添加闪光效果、将博主信息移动至文章列表的左侧、为页面图标添加鼠标悬停的跳动效果 应该 import scss

【文档错误修订】指南 -> 高级 -> 主题预设-> 样式相关

---

docs/theme/src/zh/demo/projects.md

docs: fix typos

---

packages/copy-code2/src/node/locales.ts

Hello!
Fix japanese locale in copy-code2 plugin, please reveiew.

fix(copy-code2): update ja locale 

---

packages/theme/src/node/plugins/redirect.ts

The error text confused me a bit during the update

fix: plugin missing message

---

demo/theme-docs/src/demo/page.md

Fix typo in Page Content section

chore(demo): fix typo

---

packages/md-enhance/src/client/utils/code-demo/getCode.ts

fix(md-enhance): incorrect js code wrapper, close #4355

---

packages/md-enhance/src/node/mdEnhancePlugin.ts

fix(md-enhance): fix plantuml

---

docs/theme/src/zh/demo/projects.md

Update project info in projects.md

---

docs/theme/src/zh/demo/projects.md

This pull request includes an addition to the `docs/theme/src/zh/demo/projects.md` file, specifically within the `blogs` section. The change adds a new blog entry with details such as the blog's name, description, logo, URL, repository, and a preview image.
Changes to the `blogs` section:
* Added a new blog entry for "耳朵同的博客" including its description, logo, URL, repository, and preview image.

docs(theme): add project
